apiVersion: v1
kind: Service
metadata:
  name: hotel-front
  labels:
    app: hotel-front
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 31333
  selector:
    app: hotel-front
