apiVersion: v1
kind: Service
metadata:
  name: 'hotel-view'
  labels:
    service: 'hotel-view'
  name: 'hotel-view'
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31110
  selector:
    app: 'hotel-view'