apiVersion: apps/v1 
kind: Deployment
metadata:
  name: 'hotel-interface'
  labels:
    app: 'hotel-interface'
spec:
  selector:
    matchLabels:
      app: 'hotel-interface'
  replicas: 1
  template:
    metadata:
      annotations:
        traffic.sidecar.istio.io/excludeOutboundIPRanges: 0.0.0.0/0
      labels:
        app: 'hotel-interface'
    spec:
      containers:
      - name: 'hotel-interface'
        image: devcluster.icp:8500/aib2b/hotel_interface:20190516-develop-7
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
    imagePullSecrets:
    - name: regcred