apiVersion: apps/v1 
kind: Deployment
metadata:
  name: hotel-management
  labels:
    app: hotel-management
spec:
  selector:
    matchLabels:
      app: hotel-management
  replicas: 1
  template:
    metadata:
      labels:
        app: hotel-management
    spec:
      containers:
      - name: hotel-management
        image: devcluster.icp:8500/aib2b/hotel_management:IMAGE_TAG_PLACEHOLDER
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
    imagePullSecrets:
    - name: regcred