apiVersion: v1
kind: Service
metadata:
  name: 'hotel-information'
  labels:
    app: 'hotel-information'
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 31336
  selector:
    app: 'hotel-information'