apiVersion: v1
kind: Service
metadata:
  name: 'hotel-management'
  labels:
    app: 'hotel-management'
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 31335
  selector:
    app: 'hotel-management'