apiVersion: v1
kind: Service
metadata:
  name: 'hotel-interface'
  labels:
    app: 'hotel-interface'
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 32344
  selector:
    app: 'hotel-interface'